version: '2'
services:
  db:
    image: postgres:alpine
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
    ports:
      - "80:3000"
    depends_on:
      - db
    env_file: .env